[build]
publish = "public"
command = "npm run build && hugo --gc --minify"

[context.production.environment]
HUGO_VERSION = "0.99.1"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.split1]
command = "npm run build && hugo --gc --minify --enableGitInfo"

[context.split1.environment]
HUGO_VERSION = "0.99.1"
HUGO_ENV = "production"

[context.deploy-preview]
command = "npm run build && hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"

[context.deploy-preview.environment]
HUGO_VERSION = "0.99.1"

[context.branch-deploy]
command = "npm run build && hugo --gc --minify -b $DEPLOY_PRIME_URL"

[context.branch-deploy.environment]
HUGO_VERSION = "รง"

[context.next.environment]
HUGO_ENABLEGITINFO = "true"

[[redirects]]
  from = "https://bissgigi.com/*"
  to = "https://bissgigi.art/"
  status = 301
  force = true

[[redirects]]
  from = "https://www.bissgigi.com/*"
  to = "https://bissgigi.art/"
  status = 301
  force = true
